"""Build the Arduino Foundations → Components question bank (area C).

Reads the child-facing KB markdown and emits banks/arduino-C-components.json in the
recursive node-tree import shape. Questions are written for a smart ~8-year-old with a
6th-grade ceiling: concrete, analogy-driven, short, and factually true.

Run:  python -m scripts.build_arduino_C   (from repo root)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KB = (ROOT / "research" / "arduino-foundations" / "C-components.md").read_text(encoding="utf-8")
OUT = ROOT / "banks" / "arduino-C-components.json"


def mcq(prompt, choices, answer, expl):
    return {"type": "mcq", "prompt": prompt, "choices": choices, "answer": answer, "explanation": expl}


def tf(prompt, answer, expl):
    return {"type": "truefalse", "prompt": prompt, "answer": answer, "explanation": expl}


def short(prompt, answer, expl):
    return {"type": "short", "prompt": prompt, "answer": answer, "explanation": expl}


C1 = [
    mcq("What is the main job of a resistor in a circuit?",
        ["To limit the current and keep it small", "To make more current flow",
         "To store charge for later", "To make light"], "To limit the current and keep it small",
        "A resistor resists the current — it makes it harder for current to flow, keeping it small and safe."),
    mcq("Why do we put a resistor next to an LED?",
        ["So too much current doesn't burn out the LED", "To make the LED brighter than safe",
         "To turn the LED into a battery", "To make the LED face backward"],
        "So too much current doesn't burn out the LED",
        "An LED can only take a little current. The resistor holds the current back so the LED isn't damaged."),
    mcq("What can happen if you wire an LED straight to a battery with NO resistor?",
        ["Too much current can burn out the LED", "The LED gets safer",
         "The battery turns into a resistor", "Nothing ever happens"],
        "Too much current can burn out the LED",
        "With no resistor, too much current rushes through and the LED can burn out."),
    mcq("A resistor is most like which of these?",
        ["A kink or pinch in a hose that lets less water through", "A bigger pump",
         "An open, wide-open pipe", "A bucket that stores water"],
        "A kink or pinch in a hose that lets less water through",
        "A resistor pinches the flow so less current gets through, like a kink in a hose."),
    mcq("As a resistor slows the current, a little electrical energy turns into…",
        ["Heat", "More current", "Light only", "New batteries"], "Heat",
        "A resistor turns a little of the energy into heat as it slows the current down."),
    mcq("Does it matter which way around you plug in a resistor?",
        ["No — it works either direction", "Yes — only one way works",
         "Yes — it must point at the battery", "It only works upside down"],
        "No — it works either direction",
        "A resistor has no + or − side; it works the same plugged in either way."),
    mcq("Which word best describes what a resistor does to the current?",
        ["Limits it", "Doubles it", "Creates it", "Stores it"], "Limits it",
        "A resistor limits (reduces) the current to keep it small and safe."),
    mcq("An LED can only handle a little current. How does a resistor help?",
        ["It keeps the current down to a safe amount", "It adds extra current",
         "It removes the LED's color", "It charges the LED like a battery"],
        "It keeps the current down to a safe amount",
        "The resistor holds the current back so the LED gets just enough to glow safely."),
    tf("A resistor makes it harder for current to flow.",
       "True", "That is exactly what 'resist' means — a resistor limits the current."),
    tf("A resistor's job is to make MORE current flow in a circuit.",
       "False", "A resistor does the opposite — it limits the current, making it smaller."),
    tf("Without a current-limiting resistor, too much current can burn out an LED.",
       "True", "An LED takes only a little current; with no resistor it can get too much and burn out."),
    tf("You must plug a resistor in one exact way or it won't work.",
       "False", "A resistor has no polarity — it works either way around."),
    short("What is the name of the part whose job is to limit the current in a circuit?",
          "A resistor", "A resistor resists the current, keeping it small and safe."),
    short("A resistor protects an LED by keeping the current small. What can happen to an LED with no resistor?",
          "It can burn out", "Too much current rushes through and the LED burns out."),
    short("As a resistor slows the current, what does a little of the electrical energy turn into?",
          "Heat", "A resistor turns a little energy into heat as it limits the current."),
]

C2 = [
    mcq("A diode lets current flow in how many directions?",
        ["One direction only", "Both directions equally", "No directions at all",
         "Every direction at once"], "One direction only",
        "A diode is a one-way street for current — it flows one way and is blocked the other way."),
    mcq("What does the 'L' in LED stand for?",
        ["Light", "Long", "Low", "Loop"], "Light",
        "LED stands for Light-Emitting Diode — a diode that gives off light."),
    mcq("An LED is a special kind of what?",
        ["Diode", "Resistor", "Battery", "Switch"], "Diode",
        "An LED is a Light-Emitting Diode — a diode that makes light when current flows the right way."),
    mcq("On a fresh LED, which leg is the + side (the anode)?",
        ["The longer leg", "The shorter leg", "Both legs", "Neither leg"], "The longer leg",
        "The longer leg is the + side (anode) and goes toward the positive part of the circuit."),
    mcq("What happens if you plug an LED in backward?",
        ["It doesn't light up", "It gets twice as bright", "It turns into a resistor",
         "It makes a loud sound"], "It doesn't light up",
        "Backward, current can't flow through the LED, so it simply doesn't light (it's not broken)."),
    mcq("A diode is most like which everyday thing?",
        ["A one-way street", "A two-way road", "A storage tank", "A loud bell"],
        "A one-way street",
        "A diode lets current go one way and blocks it the other way — like a one-way street."),
    mcq("Besides being plugged in the right way, what else does an LED need to stay safe?",
        ["A resistor to limit the current", "A second battery",
         "A bigger motor", "A speaker"], "A resistor to limit the current",
        "An LED needs a resistor so the current stays small and it isn't burned out."),
    mcq("Why does an LED have a + side and a − side?",
        ["Because a diode only lets current flow one way", "Because it stores charge",
         "Because it is a magnet", "Because it makes heat"],
        "Because a diode only lets current flow one way",
        "Since a diode is one-way, you must connect the LED the right way round — that's its polarity."),
    tf("A diode lets current flow only one way.",
       "True", "A diode is a one-way street — current flows forward and is blocked backward."),
    tf("An LED makes light when current flows through it the correct way.",
       "True", "LED means Light-Emitting Diode; it lights up when current flows forward."),
    tf("On a fresh LED, the SHORTER leg is the + side.",
       "False", "The LONGER leg is the + side (anode); the shorter leg is the − side."),
    tf("If you plug an LED in backward, it will glow extra bright.",
       "False", "Backward it doesn't light at all, because current can't flow through it."),
    short("A diode is the electrical version of what kind of street?",
          "A one-way street", "A diode only lets current flow one way, like a one-way street."),
    short("On a fresh LED, the longer leg is the + side. What is the + side called?",
          "The anode", "The longer leg is the anode (the + side) and goes toward positive."),
    short("What does LED stand for?",
          "Light-Emitting Diode", "An LED is a diode that emits (makes) light when current flows forward."),
]

C3 = [
    mcq("What does a capacitor do?",
        ["Stores a little electric charge and lets it back out", "Makes its own electricity from chemicals",
         "Limits the current like a resistor", "Spins around to make motion"],
        "Stores a little electric charge and lets it back out",
        "A capacitor stores a little charge on two plates and can release it again."),
    mcq("A capacitor is best pictured as…",
        ["A tiny bucket you can fill and tip out fast", "A one-way street",
         "A pump that pushes water", "A kink in a hose"],
        "A tiny bucket you can fill and tip out fast",
        "A capacitor is like a tiny, fast bucket for charge — fill it and pour it back out."),
    mcq("Inside a capacitor, charge builds up on what?",
        ["Two metal plates", "A spinning coil", "A glowing wire", "A row of magnets"],
        "Two metal plates",
        "A capacitor has two metal plates with a gap; charge builds up on the plates."),
    mcq("How is a capacitor DIFFERENT from a battery?",
        ["It only holds a little charge and fills and empties fast", "It powers things for hours and hours",
         "It makes energy from chemicals", "It can never be emptied"],
        "It only holds a little charge and fills and empties fast",
        "A battery makes energy from chemicals and lasts long; a capacitor only holds a little and charges/empties fast."),
    mcq("Does a capacitor MAKE electricity on its own?",
        ["No — it only stores charge the circuit gives it", "Yes — it makes new electricity",
         "Yes — from chemicals inside", "Yes — by spinning"],
        "No — it only stores charge the circuit gives it",
        "A capacitor doesn't make electricity; it only stores charge and gives it back."),
    mcq("One handy job a capacitor does is…",
        ["Smooth out sudden surges to keep power steady", "Turn electricity into spinning",
         "Make light", "Block current one way like a diode"],
        "Smooth out sudden surges to keep power steady",
        "A capacitor can soak up a surge and give charge back a moment later, keeping power steady."),
    mcq("Compared to a battery, how fast does a capacitor fill and empty?",
        ["Very fast", "Very slowly over hours", "It never empties", "Only once a year"],
        "Very fast",
        "A capacitor charges and discharges very quickly, unlike a slow, long-lasting battery."),
    mcq("How much charge does a capacitor hold compared with a battery?",
        ["Only a little", "Much more", "Exactly the same", "An endless amount"],
        "Only a little",
        "A capacitor holds only a little charge; a battery stores much more energy."),
    tf("A capacitor stores a little charge and can let it back out.",
       "True", "A capacitor charges up on its plates and then discharges that charge again."),
    tf("A capacitor is the same thing as a battery.",
       "False", "A battery makes energy from chemicals and lasts long; a capacitor just holds a little charge briefly."),
    tf("Inside a capacitor there are two metal plates where charge builds up.",
       "True", "Charge collects on the capacitor's two plates, separated by a gap."),
    tf("A capacitor makes brand-new electricity all by itself.",
       "False", "A capacitor only stores charge that the circuit gives it, then gives it back."),
    short("What part stores a little charge like a tiny, fast rechargeable bucket?",
          "A capacitor", "A capacitor stores a little charge and releases it quickly."),
    short("Inside a capacitor, charge builds up on two metal what?",
          "Plates", "A capacitor has two metal plates with a gap; charge builds up on them."),
    short("Which lasts and powers things far longer — a battery or a capacitor?",
          "A battery", "A battery stores much more energy and lasts longer; a capacitor holds only a little, briefly."),
]

C4 = [
    mcq("What is the simplest job of a switch?",
        ["To open or close a circuit", "To store charge",
         "To make light", "To spin a shaft"], "To open or close a circuit",
        "A switch opens the loop (off) or closes it (on) to stop or allow the current."),
    mcq("When a switch is CLOSED, what happens?",
        ["The loop is complete and current flows", "There is a gap so current stops",
         "The circuit melts", "The battery empties at once"],
        "The loop is complete and current flows",
        "Closed means the loop is complete, so current flows and the light turns on."),
    mcq("What is special about a transistor as a switch?",
        ["A small signal can flip it, with no moving parts", "It has big moving gears",
         "It makes its own electricity", "It only works under water"],
        "A small signal can flip it, with no moving parts",
        "A transistor is a switch with no moving parts that a small electric signal turns on and off."),
    mcq("The big idea behind a transistor is…",
        ["A small current controls a bigger current", "A big current controls a tiny one",
         "It stores charge like a bucket", "It spins to make motion"],
        "A small current controls a bigger current",
        "A small signal at one pin controls a bigger current through the transistor."),
    mcq("What is inside a relay that makes it work?",
        ["An electromagnet that pulls a switch closed", "A glowing light",
         "Two storage plates", "A one-way diode only"],
        "An electromagnet that pulls a switch closed",
        "A relay uses an electromagnet: a small current makes it magnetic and it pulls a switch closed."),
    mcq("A relay is often called an 'electric ___'.",
        ["lever", "bucket", "street", "magnet bottle"], "lever",
        "A relay is like an electric lever: a little push switches on a much bigger circuit."),
    mcq("Why do Arduino projects use transistors and relays?",
        ["So a small Arduino signal can control big things", "To make the Arduino slower",
         "To store charge", "To make the board lighter"],
        "So a small Arduino signal can control big things",
        "Arduino pins are weak, so transistors and relays let a little signal control big loads like a motor or lamp."),
    mcq("In a relay, what does the small current do first?",
        ["Turns the electromagnet on", "Spins a motor",
         "Lights an LED forever", "Stores itself on plates"],
        "Turns the electromagnet on",
        "The small current energizes the electromagnet, which then pulls the switch closed."),
    tf("A switch can open a circuit (off) or close it (on).",
       "True", "Closed completes the loop so current flows; open leaves a gap so current stops."),
    tf("A transistor needs big moving gears to switch on and off.",
       "False", "A transistor has no moving parts; a small electric signal flips it."),
    tf("In a relay, a small current controls a much bigger circuit.",
       "True", "The small current works an electromagnet that switches the bigger circuit on."),
    tf("A relay makes a click sound when it switches.",
       "True", "You can hear the relay click as the electromagnet pulls the switch closed."),
    short("A small signal controlling a bigger current is the big idea behind which no-moving-parts switch?",
          "A transistor", "A transistor lets a small current or voltage control a bigger current."),
    short("What part inside a relay becomes magnetic and pulls a switch closed?",
          "An electromagnet", "The small current turns on the electromagnet, which pulls the switch closed."),
    short("A relay is like an electric what — a little push moving something much bigger?",
          "A lever", "A relay is an electric lever: a small signal switches a much bigger circuit."),
]

C5 = [
    mcq("Sound is really what?",
        ["Vibration", "Light", "Heat", "Magnetism"], "Vibration",
        "Sound is vibration — something shaking pushes the air, and your ear hears it."),
    mcq("How do a buzzer and a speaker make sound?",
        ["By making a part vibrate", "By storing charge",
         "By limiting current", "By spinning a shaft fast"], "By making a part vibrate",
        "They turn electricity into sound by making a part vibrate, which wiggles the air."),
    mcq("Faster vibration makes the pitch…",
        ["Higher", "Lower", "Silent", "Backward"], "Higher",
        "More wiggles per second means a higher pitch; slower vibration is a lower pitch."),
    mcq("What makes a sound LOWER (deeper)?",
        ["Slower vibration", "Faster vibration", "More light", "More resistance"],
        "Slower vibration",
        "Slower vibration (fewer wiggles per second) makes a lower, deeper pitch."),
    mcq("What is an ACTIVE buzzer like?",
        ["It has its own tone — power it and it just buzzes one note", "It needs you to set its pitch every time",
         "It only works backward", "It stores charge"],
        "It has its own tone — power it and it just buzzes one note",
        "An active buzzer has its tone built in; give it power and it buzzes one note."),
    mcq("What does a PASSIVE buzzer or speaker need from the circuit?",
        ["To be told how fast to vibrate", "Nothing at all",
         "A diode to face backward", "A resistor to spin"],
        "To be told how fast to vibrate",
        "A passive buzzer/speaker needs the circuit to set the speed, so you can make different pitches and tunes."),
    mcq("Many speakers use a coil and a magnet to…",
        ["Push and pull a cone so it vibrates the air", "Store charge on two plates",
         "Block current one way", "Make heat to limit current"],
        "Push and pull a cone so it vibrates the air",
        "Changing current makes the coil push/pull against the magnet, vibrating a cone that moves the air."),
    mcq("The speed of a vibration (how many wiggles per second) is called its…",
        ["Frequency", "Voltage", "Resistance", "Polarity"], "Frequency",
        "Frequency is how fast something vibrates; higher frequency means higher pitch."),
    tf("Sound is made by something vibrating.",
       "True", "When something shakes quickly it pushes the air, and that reaches your ear as sound."),
    tf("A buzzer turns electricity into sound by making a part vibrate.",
       "True", "Electricity makes a small piece move back and forth fast, wiggling the air into sound."),
    tf("Slower vibration makes a higher, squeakier pitch.",
       "False", "Faster vibration makes a higher pitch; slower makes a lower, deeper pitch."),
    tf("A passive buzzer needs the circuit to tell it how fast to vibrate.",
       "True", "That's why a passive buzzer can make different pitches and little tunes."),
    short("Sound is really a kind of fast back-and-forth movement. What is that movement called?",
          "Vibration", "Sound is vibration — shaking that pushes the air to your ear."),
    short("Faster vibration makes a higher pitch. What makes a LOWER pitch?",
          "Slower vibration", "Slower vibration (fewer wiggles per second) makes a lower, deeper pitch."),
    short("What word means how fast something vibrates — which sets the pitch?",
          "Frequency", "Frequency is how fast something vibrates; higher frequency = higher pitch."),
]

C6 = [
    mcq("A motor turns electricity into what?",
        ["Motion", "Sound", "Stored charge", "Light only"], "Motion",
        "A motor turns electricity into motion (spinning or movement)."),
    mcq("What is the secret ingredient that makes a motor move?",
        ["Magnetism", "Static charge sitting still", "Sound waves", "Stored heat"],
        "Magnetism",
        "Current in a coil makes an electromagnet, and magnets pushing/pulling make the motor spin."),
    mcq("When current flows through a coil of wire, the coil becomes a…",
        ["An electromagnet", "A resistor", "A capacitor", "A diode"], "An electromagnet",
        "A coil with current flowing is an electromagnet — a magnet you can switch on and off."),
    mcq("What does a plain DC motor do when you give it power?",
        ["Spins fast and continuously", "Turns to one exact angle and stops",
         "Moves one tiny click", "Stores charge"], "Spins fast and continuously",
        "A DC motor just spins continuously — great for wheels and fans."),
    mcq("What is special about a SERVO motor?",
        ["It turns to a set angle and holds there", "It spins freely forever",
         "It only makes sound", "It stores charge"], "It turns to a set angle and holds there",
        "A servo turns to an angle you choose (like 90°) and holds it — good for steering and robot arms."),
    mcq("What is special about a STEPPER motor?",
        ["It moves in small, precise steps", "It can only spin one full speed",
         "It makes light", "It never stops"], "It moves in small, precise steps",
        "A stepper moves one precise step at a time by switching its electromagnets in order."),
    mcq("Magnets push and pull on each other. Which is true?",
        ["Opposite poles attract; same poles repel", "Same poles attract; opposite poles repel",
         "Magnets never push or pull", "Magnets only pull, never push"],
        "Opposite poles attract; same poles repel",
        "A motor uses this pushing and pulling to make the shaft spin."),
    mcq("Why does a motor often need a transistor to switch it on?",
        ["A motor needs more current than an Arduino pin can give", "A transistor makes the motor quieter",
         "A transistor stores the motor's charge", "A motor cannot use electricity"],
        "A motor needs more current than an Arduino pin can give",
        "Arduino pins are weak, so a transistor lets the small pin signal switch the motor's bigger current."),
    mcq("Which motor would be best to move an EXACT amount, like in a 3D printer?",
        ["A stepper motor", "A plain DC motor", "A buzzer", "A capacitor"],
        "A stepper motor",
        "A stepper moves in precise steps, so it's great when you need an exact amount of motion."),
    tf("A motor uses electricity and magnetism to make motion.",
       "True", "Current makes a coil into an electromagnet, and magnets push/pull to spin the shaft."),
    tf("A DC motor turns to one set angle and holds, like a servo.",
       "False", "A DC motor spins continuously; a SERVO is the one that turns to a set angle and holds."),
    tf("A coil of wire with current flowing through it acts like a magnet.",
       "True", "That's an electromagnet — a magnet you can switch on and off with electricity."),
    tf("A stepper motor moves in small, precise steps.",
       "True", "It clicks one step at a time by switching its electromagnets in order."),
    short("A motor turns electricity into motion using which invisible force?",
          "Magnetism", "Current makes an electromagnet, and magnets push/pull to create the motion."),
    short("Which motor turns to a set angle and holds there — DC, servo, or stepper?",
          "Servo", "A servo turns to the angle you choose and holds it, good for steering and arms."),
]

BANK = {
    "topic": {
        "name": "Arduino Foundations",
        "description": "The science and coding ideas you need to understand the Elegoo Arduino kit — built for a curious grade-schooler.",
        "teaching_notes": "Target level: a smart 8-year-old, grade-6 ceiling. Keep it concrete and analogy-driven (water-in-pipes for electricity). Pair each area with its hands-on tool (PhET sims, Blockly Games). Simplifications must stay TRUE.",
    },
    "children": [
        {
            "name": "Components",
            "source": {
                "title": "Components — knowledge base",
                "content": KB,
            },
            "children": [
                {"name": "Resistors", "questions": C1},
                {"name": "LEDs & Diodes", "questions": C2},
                {"name": "Capacitors", "questions": C3},
                {"name": "Switches, Transistors & Relays", "questions": C4},
                {"name": "Buzzers & Speakers", "questions": C5},
                {"name": "Motors", "questions": C6},
            ],
        },
    ],
}


def main():
    OUT.write_text(json.dumps(BANK, indent=2, ensure_ascii=False), encoding="utf-8")
    n = sum(len(leaf["questions"]) for leaf in BANK["children"][0]["children"])
    print(f"Wrote {OUT.relative_to(ROOT)} — {n} questions across "
          f"{len(BANK['children'][0]['children'])} sub-topics.")


if __name__ == "__main__":
    main()
