"""Build the Arduino Foundations → Programming Basics question bank (area E).

Reads the child-facing KB markdown and emits banks/arduino-E-programming.json in the
recursive node-tree import shape. Questions are written for a smart ~8-year-old with a
6th-grade ceiling: concrete, concept-driven, short, and factually true. Keep it about
ideas (sequence, decisions, repeating) tied to setup()/loop() and block-coding — not
heavy syntax.

Run:  python -m scripts.build_arduino_E   (from repo root)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KB = (ROOT / "research" / "arduino-foundations" / "E-programming.md").read_text(encoding="utf-8")
OUT = ROOT / "banks" / "arduino-E-programming.json"


def mcq(prompt, choices, answer, expl):
    return {"type": "mcq", "prompt": prompt, "choices": choices, "answer": answer, "explanation": expl}


def tf(prompt, answer, expl):
    return {"type": "truefalse", "prompt": prompt, "answer": answer, "explanation": expl}


def short(prompt, answer, expl):
    return {"type": "short", "prompt": prompt, "answer": answer, "explanation": expl}


E1 = [
    mcq("A step-by-step list of exact instructions to do a task or solve a problem is called…",
        ["An algorithm", "A magnet", "A volt", "A battery"], "An algorithm",
        "An algorithm is a precise, step-by-step list of instructions, like a recipe."),
    mcq("Which of these is a good everyday example of an algorithm?",
        ["The steps in a recipe to bake cookies", "The color of a wire",
         "How heavy a rock is", "The weather today"], "The steps in a recipe to bake cookies",
        "A recipe is an everyday algorithm — an ordered list of steps."),
    mcq("When a computer runs a program, it follows the steps…",
        ["Exactly, and in the order given", "However it feels like",
         "By guessing what you meant", "All at the same time, randomly"],
        "Exactly, and in the order given",
        "A computer is fast but not clever — it does exactly what you say, in order."),
    tf("A computer can guess what you really meant if you write a step in the wrong place.",
       "False", "Computers do exactly what they're told, in order — they don't guess your meaning."),
    tf("A program is a set of instructions a computer follows to do a job.",
       "True", "A program is the instructions; the plan behind it is the algorithm."),
    short("What word means a precise, step-by-step list of instructions to do a task?",
          "Algorithm", "An algorithm is the step-by-step plan a program follows."),
    mcq("Why does the ORDER of the steps matter in an algorithm?",
        ["The computer does each step in turn, so wrong order gives the wrong result",
         "It doesn't matter at all", "Computers shuffle the steps anyway",
         "Order only matters for drawings"],
        "The computer does each step in turn, so wrong order gives the wrong result",
        "Steps run in order; out-of-order steps make the computer do the wrong thing."),
    mcq("A small mistake that breaks a program is nicknamed a…",
        ["Bug", "Beetle snack", "Volt", "Loop"], "Bug",
        "A bug is a mistake in a program; even a tiny one can break it."),
    mcq("Which is the BEST first step in an algorithm for 'make toast'?",
        ["Get the bread", "Eat the toast", "Wash the dishes", "Turn off the lights"], "Get the bread",
        "You need the bread before you can toast it — order matters."),
    tf("The steps in an algorithm should be clear and exact, with no 'you know what I mean.'",
       "True", "Each step must be clear and unambiguous so the computer can follow it."),
    tf("Stacking blocks from top to bottom in Scratch is one way to write a program.",
       "True", "Those stacked, ordered blocks are the program; the ordered steps are the algorithm."),
    mcq("A computer is best described as…",
        ["Fast but not clever — it follows exact instructions",
         "Clever enough to fix your mistakes", "Able to read your mind",
         "Slower than a person at math"], "Fast but not clever — it follows exact instructions",
        "Computers are fast but only do exactly what the instructions say."),
    short("True or false: a recipe is an example of an everyday algorithm.",
          "True", "A recipe is an ordered list of exact steps — an everyday algorithm."),
    mcq("If you swap two steps of an algorithm by accident, what usually happens?",
        ["The computer may do the wrong thing", "The computer fixes it for you",
         "Nothing ever changes", "The steps reorder themselves"],
        "The computer may do the wrong thing",
        "The computer follows the steps as written, so wrong order can give wrong results."),
    short("What is the nickname for a mistake in a program that makes it break?",
          "A bug", "A bug is an error in a program; finding and fixing them is debugging."),
]

E2 = [
    mcq("On an Arduino, how many times does setup() run?",
        ["Once, at the start", "Forever, over and over", "Never", "Ten times"], "Once, at the start",
        "setup() runs one time at the start, when the board powers on or is reset."),
    mcq("On an Arduino, how many times does loop() run?",
        ["Over and over, repeating forever", "Exactly once", "Never", "Only twice"],
        "Over and over, repeating forever",
        "loop() repeats again and again until the board is turned off or reset."),
    mcq("Which Arduino function runs FIRST?",
        ["setup()", "loop()", "delay()", "They run at the same time"], "setup()",
        "setup() always runs once before loop() starts repeating."),
    tf("loop() runs after setup(), and then keeps repeating.",
       "True", "First setup() runs once, then loop() repeats forever."),
    tf("setup() repeats over and over while the Arduino is on.",
       "False", "setup() runs only ONCE at the start; loop() is the part that repeats."),
    short("Which Arduino function repeats forever: setup() or loop()?",
          "loop()", "loop() repeats forever; setup() runs only once at the start."),
    mcq("'Sequence' in a program means the steps run…",
        ["In order, one after another", "All at once", "In a random order",
         "Backwards"], "In order, one after another",
        "Sequence means top-to-bottom order, one step after another."),
    mcq("Which job belongs in setup() — the part that runs once?",
        ["Getting a pin ready as an output", "The LED blinking forever",
         "Repeating a beep many times", "Counting up forever"],
        "Getting a pin ready as an output",
        "setup() is for one-time getting-ready steps, like setting a pin's mode."),
    mcq("The Blink program turns the LED on, waits, off, waits — and it keeps blinking because that code is in…",
        ["loop()", "setup()", "a variable", "an insulator"], "loop()",
        "loop() repeats, so the on/off steps run again and again — the LED blinks."),
    tf("setup() always runs before loop().",
       "True", "The order is fixed: setup() once first, then loop() repeats."),
    mcq("In Scratch, the Arduino loop() is most like which block?",
        ["A 'forever' block", "A 'set variable' block", "A 'say hello' block",
         "A green triangle play button only"], "A 'forever' block",
        "Wrapping blocks in a 'forever' block repeats them, just like loop()."),
    mcq("What is an Arduino program usually called?",
        ["A sketch", "A doodle", "A volt", "A bug"], "A sketch",
        "An Arduino program is called a sketch."),
    tf("You should set up a pin in setup() before using it to blink an LED in loop().",
       "True", "Get the pin ready once in setup(); then loop() uses it to blink."),
    short("How many times does setup() run on an Arduino?",
          "Once", "setup() runs a single time at the start, then loop() takes over."),
    short("What word means the steps of a program run in order, one after another?",
          "Sequence", "Sequence is top-to-bottom order, one step after the next."),
]

E3 = [
    mcq("A variable is best described as…",
        ["A labeled box that holds a value", "A kind of battery",
         "A type of wire", "A blinking light"], "A labeled box that holds a value",
        "A variable is a named box; the computer remembers the value inside."),
    mcq("Why is a variable called a 'variable'?",
        ["Its value can change", "It is always the number 1",
         "It can never change", "It is made of metal"], "Its value can change",
        "It's called a variable because the value inside can vary (change)."),
    mcq("In Arduino, the data type 'int' holds what kind of value?",
        ["A whole number", "A single letter", "A picture", "A sound"], "A whole number",
        "int is short for integer — a whole number like 5, 0, or -3."),
    tf("A variable has a name so you can use the name instead of repeating the value.",
       "True", "Naming the box lets you reuse it and change it in one place."),
    tf("Once you put a value in a variable, it can never be changed.",
       "False", "A variable can change — you can put a new value in and replace the old one."),
    short("What do we call a named box that holds a value the computer remembers?",
          "A variable", "A variable is a labeled box holding a value that can change."),
    mcq("Which value would fit best in an 'int' variable?",
        ["7", "the letter Q", "3.5", "a song"], "7",
        "An int holds whole numbers; 7 is a whole number."),
    mcq("The code int count = 0; does what?",
        ["Makes a box named count with 0 inside", "Deletes a variable",
         "Turns on an LED", "Waits one second"], "Makes a box named count with 0 inside",
        "It makes an int variable named count and stores 0 in it."),
    mcq("After int count = 0; you run count = count + 1; — what is in count now?",
        ["1", "0", "2", "count"], "1",
        "0 + 1 = 1, so the box named count now holds 1."),
    mcq("Which data type would you use for a true/false value?",
        ["bool", "int", "char", "float"], "bool",
        "A bool holds true or false."),
    tf("'int' is short for the word integer, which means a whole number.",
       "True", "int = integer = a whole number with no fraction."),
    tf("A variable's name and its value are the same thing.",
       "False", "The name is the label on the box; the value is what's inside it."),
    short("What kind of number does an 'int' hold — whole numbers or numbers with decimals?",
          "Whole numbers", "int holds whole numbers like 5, 0, or -3 (no decimal point)."),
    mcq("In Scratch, which block changes the value stored in a variable?",
        ["The 'set' or 'change' block", "The 'forever' block",
         "The 'play sound' block", "The 'when green flag clicked' block"],
        "The 'set' or 'change' block",
        "Scratch's set/change blocks update a variable's value — same idea as a box you refill."),
    short("True or false: the value inside a variable can change later.",
          "True", "That's exactly why it's called a variable — its value can vary."),
]

E4 = [
    mcq("A function is best described as…",
        ["A named action you can call (run) by its name", "A kind of battery",
         "A whole number", "A type of wire"], "A named action you can call (run) by its name",
        "A function is a named mini-program you can run by its name, again and again."),
    mcq("In delay(1000), what does the 1000 do?",
        ["Tells the function to wait 1000 milliseconds", "Names the function",
         "Turns on 1000 LEDs", "Is the answer it gives back"],
        "Tells the function to wait 1000 milliseconds",
        "1000 is the input — wait 1000 ms, which is 1 second."),
    mcq("delay(1000) makes the Arduino wait about how long?",
        ["1 second", "1 minute", "1 hour", "No time at all"], "1 second",
        "1000 milliseconds = 1 second, because milli means one-thousandth."),
    mcq("The values you put inside a function's parentheses ( ) are called its…",
        ["Inputs", "Colors", "Bugs", "Wires"], "Inputs",
        "Inputs (also called arguments) tell the function exactly what to do."),
    mcq("How many inputs does digitalWrite(pin, HIGH) take?",
        ["Two", "Zero", "One", "Ten"], "Two",
        "It takes two inputs: which pin, and whether to make it HIGH (on) or LOW (off)."),
    tf("digitalWrite(pin, HIGH) turns a pin ON.",
       "True", "HIGH turns the pin on; LOW turns it off."),
    short("What is the name for a named action you can call to run its steps?",
          "A function", "A function is a named action you can call by name as often as you like."),
    mcq("Why is it handy to write your own function?",
        ["You can reuse its steps by name instead of rewriting them",
         "It makes the computer slower", "It deletes your program",
         "It changes the voltage"], "You can reuse its steps by name instead of rewriting them",
        "A function lets you call the same steps again without retyping them."),
    mcq("Which of these is a real Arduino function?",
        ["delay()", "battery()", "rubber()", "atom()"], "delay()",
        "delay() is a real Arduino function; you give it a number of milliseconds to wait."),
    tf("Some functions give back a value (a result) you can use.",
       "True", "Many functions return a result; others just do an action like waiting."),
    mcq("pinMode(pin, OUTPUT) is usually called inside which part of the program?",
        ["setup()", "loop()", "a variable", "an operator"], "setup()",
        "Getting a pin ready is a one-time job, so it goes in setup()."),
    tf("A function can take inputs to tell it exactly what to do.",
       "True", "Inputs go inside the parentheses, like delay(1000) or digitalWrite(pin, HIGH)."),
    mcq("In Scratch, making and naming your own block is most like…",
        ["Writing your own function", "Making a variable",
         "Adding a battery", "Drawing a sprite"], "Writing your own function",
        "Scratch 'My Blocks' are functions you create and name, then call."),
    short("In delay(1000), is the 1000 an input the function uses, or the function's name?",
          "An input", "1000 is the input telling delay how long to wait (1000 ms)."),
    short("What does the word HIGH do in digitalWrite(pin, HIGH)?",
          "Turns the pin on", "HIGH means on; LOW means off."),
]

E5 = [
    mcq("An 'if' statement lets a program…",
        ["Do something only when a condition is true", "Repeat steps forever",
         "Hold a number in a box", "Measure voltage"],
        "Do something only when a condition is true",
        "An if runs its steps only when its condition is true."),
    mcq("What is a 'condition' in an if statement?",
        ["A question with a true/false answer", "A kind of battery",
         "A whole number box", "The name of a pin"],
        "A question with a true/false answer",
        "A condition is a yes/no question, like 'is the button pressed?'"),
    mcq("What does 'else' do?",
        ["Gives a backup action for when the condition is false",
         "Repeats the steps 10 times", "Stores a number",
         "Turns the board off"], "Gives a backup action for when the condition is false",
        "else runs only when the if's condition is NOT true."),
    tf("In an if/else, only ONE of the two paths runs each time.",
       "True", "If the condition is true, the if path runs; if false, the else path runs."),
    tf("An if statement always runs its steps no matter what.",
       "False", "It runs its steps only when its condition is true."),
    short("What word starts a decision that runs only when a condition is true?",
          "if", "An if statement runs its steps only when its condition is true."),
    mcq("'IF it is raining THEN take an umbrella, ELSE wear a hat.' If it is NOT raining, you…",
        ["Wear a hat", "Take an umbrella", "Do both", "Do nothing ever"], "Wear a hat",
        "The condition (raining) is false, so the else action (wear a hat) runs."),
    mcq("On Arduino: if (buttonPressed) turn LED on, else turn LED off. When the button is pressed, the LED is…",
        ["On", "Off", "Blinking randomly", "Removed"], "On",
        "The condition is true, so the if path runs and the LED turns on."),
    mcq("What kind of answer does a condition give?",
        ["True or false", "A color", "A whole song", "A voltage"], "True or false",
        "Conditions answer true or false (yes or no)."),
    tf("'else' gives a backup plan for when the condition is not true.",
       "True", "else is the path that runs when the condition is false."),
    mcq("In Scratch/Blockly, making a decision uses which block?",
        ["The 'if … then' block", "The 'forever' block",
         "The 'set variable' block", "The 'play sound' block"], "The 'if … then' block",
        "The 'if … then' (and 'if … then … else') blocks make decisions."),
    mcq("Which is a good example of a condition?",
        ["Is count greater than 5?", "Take the toast out",
         "Copper is a metal", "Wait 1 second"], "Is count greater than 5?",
        "A condition is a true/false question, like 'is count greater than 5?'"),
    tf("If the condition is false and there is an else, the else steps run.",
       "True", "False condition → the else path runs instead."),
    short("In an if/else, which part runs when the condition is FALSE?",
          "The else part", "When the condition is false, the else (backup) steps run."),
    short("True or false: a condition is a question that answers true or false.",
          "True", "Conditions answer true/false, and that decides which path runs."),
]

E6 = [
    mcq("A loop in a program is used to…",
        ["Repeat steps", "Store a number", "Measure voltage", "Name a function"],
        "Repeat steps",
        "A loop repeats steps so you don't have to write them over and over."),
    mcq("A 'for' loop repeats…",
        ["A set number of times", "Forever, no matter what",
         "Only if it rains", "Never"], "A set number of times",
        "A for loop runs a set number of times, like 'do this 10 times.'"),
    mcq("A 'while' loop repeats…",
        ["As long as a condition stays true", "Exactly once",
         "A set number of times only", "Never"],
        "As long as a condition stays true",
        "A while loop keeps going while its condition is true and stops when it's false."),
    tf("A loop saves you from writing the same steps over and over.",
       "True", "That's the point of a loop — repeat steps without rewriting them."),
    tf("A 'for' loop is best when you want to repeat something a set number of times.",
       "True", "for repeats a known number of times; while repeats while a condition holds."),
    short("Which loop repeats a set number of times: 'for' or 'while'?",
          "for", "A for loop repeats a set number of times, like 5 times."),
    mcq("To blink an LED exactly 5 times, which loop fits best?",
        ["A for loop", "A while loop that never stops",
         "No loop at all", "An if statement"], "A for loop",
        "A for loop repeats a set number of times — perfect for 'blink 5 times.'"),
    mcq("To keep beeping WHILE a button is held down, which loop fits best?",
        ["A while loop", "A for loop that runs once",
         "An if with no loop", "A variable"], "A while loop",
        "A while loop runs as long as its condition (button held) stays true."),
    mcq("A loop whose condition never becomes false will…",
        ["Never stop (an infinite loop)", "Stop right away",
         "Run exactly twice", "Turn into a variable"], "Never stop (an infinite loop)",
        "If the condition never goes false, the while loop runs forever — an infinite loop."),
    tf("Arduino's loop() is meant to repeat forever on purpose.",
       "True", "loop() is an on-purpose forever loop — the main repeating part of a sketch."),
    mcq("In Blockly Games: Maze, a 'repeat' loop helps you…",
        ["Walk the path using fewer blocks", "Change a variable's name",
         "Add a battery", "Slow the computer down"], "Walk the path using fewer blocks",
        "A repeat loop runs the same move steps several times, so you write fewer blocks."),
    mcq("A while loop stops when its condition becomes…",
        ["False", "True", "Bigger", "A whole number"], "False",
        "A while loop keeps going while the condition is true and stops when it turns false."),
    tf("A 'while' loop repeats as long as its condition is true.",
       "True", "It runs while the condition holds and stops when it becomes false."),
    short("What is the name for a loop that never stops because its condition is never false?",
          "An infinite loop", "An infinite loop runs forever; loop() is the on-purpose kind."),
    short("Which loop repeats AS LONG AS a condition stays true: 'for' or 'while'?",
          "while", "A while loop repeats while its condition is true."),
]

E7 = [
    mcq("In code, what does a single equals sign '=' mean?",
        ["Put a value into the box (assignment)", "Is it equal?",
         "Greater than", "Less than"], "Put a value into the box (assignment)",
        "= is assignment: x = 5 puts 5 into x. It does not ask a question."),
    mcq("In code, what does the double equals sign '==' mean?",
        ["Is it equal? (a true/false question)", "Put a value into the box",
         "Add two numbers", "Greater than"], "Is it equal? (a true/false question)",
        "== compares two values and answers true or false."),
    mcq("What does the '>' symbol mean?",
        ["Greater than", "Less than", "Equal to", "Plus"], "Greater than",
        "> means greater than (bigger). For example, 7 > 3 is true."),
    mcq("What does the '<' symbol mean?",
        ["Less than", "Greater than", "Equal to", "Times"], "Less than",
        "< means less than (smaller). For example, 2 < 9 is true."),
    mcq("Is 7 > 3 true or false?",
        ["True", "False", "Both", "Neither"], "True",
        "7 is greater than 3, so 7 > 3 is true."),
    tf("'x = 5' puts the value 5 into the variable x.",
       "True", "A single = is assignment — it stores 5 in x."),
    tf("'x == 5' asks the question 'is x equal to 5?'",
       "True", "Double == compares and answers true or false."),
    short("Which sign means 'put a value into the box': = or ==?",
          "=", "A single = is assignment; it stores a value in a variable."),
    short("Which sign asks 'is it equal?': = or ==?",
          "==", "Double == is the compare-for-equal question, answering true or false."),
    mcq("Is 2 < 9 true or false?",
        ["True", "False", "Both", "Neither"], "True",
        "2 is less than 9, so 2 < 9 is true."),
    mcq("A symbol that does something to values (like + or >) is called an…",
        ["Operator", "Algorithm", "Insulator", "Atom"], "Operator",
        "Operators are symbols like + - * / and the compare symbols = == > <."),
    mcq("The comparisons like '>' and '==' are exactly what an 'if' uses as its…",
        ["Condition", "Battery", "Variable name", "Function input"], "Condition",
        "An if checks a condition, and comparisons give the true/false answer it needs."),
    tf("'>' means less than.",
       "False", "> means greater than (bigger); < means less than."),
    mcq("Which common mix-up should you watch out for?",
        ["Using = (assign) when you meant == (compare)",
         "Using + when you meant a battery", "Spelling 'loop' with two o's",
         "Counting to ten"], "Using = (assign) when you meant == (compare)",
        "= puts a value in a box; == asks if two values are equal — easy to mix up."),
    short("In math and code, what is the symbol '>' read as?",
          "Greater than", "> means greater than; for example 7 > 3 is true."),
]

BANK = {
    "topic": {
        "name": "Arduino Foundations",
        "description": "The science and coding ideas you need to understand the Elegoo Arduino kit — built for a curious grade-schooler.",
        "teaching_notes": "Target level: a smart 8-year-old, grade-6 ceiling. Keep it concrete and analogy-driven (water-in-pipes for electricity). Pair each area with its hands-on tool (PhET sims, Blockly Games). Simplifications must stay TRUE.",
    },
    "children": [
        {
            "name": "Programming Basics",
            "source": {
                "title": "Programming Basics — knowledge base",
                "content": KB,
            },
            "children": [
                {"name": "What a Program Is", "questions": E1},
                {"name": "Setup & Loop", "questions": E2},
                {"name": "Variables & Data Types", "questions": E3},
                {"name": "Functions", "questions": E4},
                {"name": "If / Else (Making Decisions)", "questions": E5},
                {"name": "Loops (Repeating)", "questions": E6},
                {"name": "Comparing & Operators", "questions": E7},
            ],
        },
    ],
}


def main():
    OUT.write_text(json.dumps(BANK, indent=2, ensure_ascii=False), encoding="utf-8")
    n = sum(len(leaf["questions"]) for leaf in BANK["children"][0]["children"])
    print(f"Wrote {OUT.relative_to(ROOT)} — {n} questions across "
          f"{len(BANK['children'][0]['children'])} sub-topics.")


if __name__ == "__main__":
    main()
